#
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: [windows-2019]  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on 
  
    env:      
      Wap_Project_Path: Biztalk.Integrations.Process.sln  
      Dir_Path: C:\
      
    steps:
    - uses: actions/checkout@master
      
    - name: Checkout
      uses: actions/checkout@v2
      

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Create the app package
      run: msbuild $env:Wap_Project_Path /p:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          **/bin/Release/*.dll
    
  download:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: ./artifacts

    - name: Copy artifacts to local folder
      run: |
        New-Item -ItemType Directory -Force -Path "C:\ShashankWork\CICDDemo\"
        Copy-Item -Path "./artifacts/*" -Destination "C:\ShashankWork\CICDDemo\" -Recurse


    - name: Run a one-line script
      run: powershell C:\Temp\BizTalkDeploy.ps1

    - name: Run a one-line script
      run: powershell C:\Temp\BizTalkDeploy.ps1

