
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: self-hosted  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

  
    env:
      
      Wap_Project_Path: Corcentric.Integrations.Process.Schemas                      

    steps:
    - uses: actions/checkout@master
      
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0



      
      
